In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
df = pd.read_csv('data/scag_riverside_cleaned.csv')

C:\Users\Monisha\AppData\Local\Temp\ipykernel_5580\1889590468.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/scag_riverside_cleaned.csv')

In [3]:
df_SB = pd.read_csv('data/scag_san_bernardino_cleaned.csv')

In [4]:
df_SB.head()

,PID19,APN19,COUNTY,CITY,ACRES,IL_RATIO,LU19,LU16,JURISDICTI,LU19_CLASS,SCAG_ZN_CO,Shape_Leng,Shape_Area,geometry
0,710010829107,10829107.0,San Bernardino,Ontario,9.363185,0.00000,1262.0,1262.0,Ontario,Education,1241.0,942.166245,55418.334428,"POLYGON ((-13093624.0169 4040192.3572999984, -..."
1,710010829113,10829113.0,San Bernardino,Ontario,1.866910,0.00000,1820.0,1820.0,Ontario,Open Space and Recreation,1800.0,552.522162,11049.799596,"POLYGON ((-13093575.5007 4040192.2478, -130935..."
2,710010829114,10829114.0,San Bernardino,Ontario,1.871418,0.00000,1820.0,1820.0,Ontario,Open Space and Recreation,1800.0,552.755225,11076.464568,"POLYGON ((-13093526.8672 4040192.1378000006, -..."
3,710010830101,10830101.0,San Bernardino,Ontario,0.138351,1.83333,1110.0,1111.0,Ontario,Single Family Residential,1112.0,123.689401,818.849787,"POLYGON ((-13094243.7335 4039966.1221999973, -..."
4,710010830102,10830102.0,San Bernardino,Ontario,0.138364,1.85573,1110.0,1111.0,Ontario,Single Family Residential,1112.0,123.696903,818.920194,POLYGON ((-13094243.725200001 4039946.91910000...

In [5]:
#merge data frames

df = pd.concat([df,df_SB], ignore_index=True)

In [6]:
df.sample(5)

,PID19,APN19,COUNTY,CITY,ACRES,IL_RATIO,LU19,LU16,JURISDICTI,LU19_CLASS,SCAG_ZN_CO,Shape_Leng,Shape_Area,geometry
1506377,710104828327,104828327.0,San Bernardino,Ontario,0.213591,1.85714,1110.0,1111.0,Ontario,Single Family Residential,1112.0,149.694938,1263.811383,"POLYGON ((-13097669.9428 4038351.599100001, -1..."
491636,650501025010,501025010,Riverside,Palm Springs,0.028858,2.63468,1311.0,1311.0,Palm Springs,Industrial,9999.0,64.154115,169.918225,POLYGON ((-12972569.068799999 4009846.60239999...
1306063,710048616206,48616206.0,San Bernardino,Unincorporated,0.160318,0.00000,3000.0,1112.0,San Bernardino County (Unincorporated),Vacant,1110.0,142.552497,987.830080,"POLYGON ((-13068844.7733 4265958.661799997, -1..."
1407159,710064712219,64712219.0,San Bernardino,Unincorporated,0.137468,0.00000,3000.0,8888.0,San Bernardino County (Unincorporated),Vacant,1800.0,131.085000,813.346800,"POLYGON ((-12737423.1983 4045548.3334000036, -..."
1465829,710102049202,102049202.0,San Bernardino,Chino,0.137632,2.07764,1110.0,1111.0,Chino,Single Family Residential,1110.0,117.737460,813.155040,POLYGON ((-13099599.936900001 4029849.10270000...

In [7]:
#drop geometry
df = df.drop(['PID19','CITY','LU19','LU16','JURISDICTI','SCAG_ZN_CO','Shape_Leng','Shape_Area'], axis=1)

In [8]:
#get land use dummies
dummy_df = pd.get_dummies(df['LU19_CLASS'],prefix='LU19')

In [9]:
dummy_df.sample(5)

,LU19_Agriculture,LU19_Commercial and Services,LU19_Education,LU19_Facilities,LU19_General Office,LU19_Industrial,LU19_Military Installations,LU19_Mixed Commercial and Industrial,LU19_Mixed Residential,LU19_Mixed Residential and Commercial,...,LU19_Open Space and Recreation,LU19_Rural Residential,LU19_Single Family Residential,LU19_Specific Plan,"LU19_Transportation, Communications, and Utilities",LU19_Under Construction,LU19_Undevelopable,LU19_Unknown,LU19_Vacant,LU19_Water
22687,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1151317,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1114508,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
171706,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1619792,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [10]:
df = pd.concat([df, dummy_df], axis=1)

In [11]:
df.head(5)

,APN19,COUNTY,ACRES,IL_RATIO,LU19_CLASS,geometry,LU19_Agriculture,LU19_Commercial and Services,LU19_Education,LU19_Facilities,...,LU19_Open Space and Recreation,LU19_Rural Residential,LU19_Single Family Residential,LU19_Specific Plan,"LU19_Transportation, Communications, and Utilities",LU19_Under Construction,LU19_Undevelopable,LU19_Unknown,LU19_Vacant,LU19_Water
0,101020001,Riverside,14.741652,0.0,Open Space and Recreation,"POLYGON ((-13097089.523 4017893.217100002, -13...",0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,101020003,Riverside,395.960980,0.0,Open Space and Recreation,"POLYGON ((-13094003.1127 4018653.675999999, -1...",0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,101020004,Riverside,550.001027,0.0,Open Space and Recreation,"POLYGON ((-13094733.9646 4018668.417300001, -1...",0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,101020005,Riverside,83.605097,0.0,Open Space and Recreation,"POLYGON ((-13097089.523 4017893.217100002, -13...",0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,101030001,Riverside,89.429098,0.0,Open Space and Recreation,POLYGON ((-13093605.421500001 4018643.95920000...,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [12]:
df.to_csv('data/SCAG_clean.csv')