In [1]:
import geopandas as gpd

In [2]:
riverside = gpd.read_file('data/riversidegeom/Udsparcels.shp')
riverside.head()

,APN,FLAG,MAIL_STREE,MAIL_CITY,SITUS_STRE,SITUS_CITY,STREET_NUM,STREET_PRE,STREET_NAM,STREET_TYP,...,BLOCK,CAME_FROM,TAX_RATE_A,LAND,STRUCTURES,PRIMARY_OW,ALL_OWNER_,Shape_Leng,Shape_Area,geometry
0,727271026,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,750.928966,20576.810542,"POLYGON ((6614112.612 2150594.430, 6614159.734..."
1,779201018,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,269.157285,3783.144844,"POLYGON ((6570999.526 2188909.899, 6570971.279..."
2,182084014,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1118.738635,8969.624746,"POLYGON ((6204064.073 2310041.573, 6204067.037..."
3,290080018,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1294.601223,97648.076503,"POLYGON ((6196599.470 2223714.710, 6196589.146..."
4,300090005,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,3208.975260,559323.813624,"POLYGON ((6272976.191 2246330.019, 6272976.353..."